name = "ITensorsVisualization"
uuid = "f2aed53d-2f32-47c3-a7b9-1ee253853786"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.1.0"

[deps]
GraphRecipes = "bd48cda9-67a9-57be-86fa-5b3c104eda73"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Plots = "1.10"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
