name = "ITensorsVisualization"
uuid = "f2aed53d-2f32-47c3-a7b9-1ee253853786"
authors = ["Matthew Fishman <mfishman@flatironinstitute.org> and contributors"]
version = "0.1.2"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NetworkLayout = "46757867-2c16-5918-afeb-47bfcb05e46a"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
GLMakie = "0.1.26, 0.4"
ITensors = "0.1.38"
NetworkLayout = "0.3"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
